---
global:
    name: consul
    datacenter: stack

server:
    extraConfig: |
      {
        "acl": {
          "enabled": true,
          "default_policy": "deny",
          "enable_token_persistence": true,
          "down_policy": "extend-cache"
        }
      }

client:
    extraConfig: |
      {
        "acl": {
          "enabled": true,
          "default_policy": "deny",
          "enable_token_persistence": true,
          "down_policy": "extend-cache",
          "tokens": {
            "agent": "{{ .Values.agentToken }}"
          }
        }
      }
