---
- hosts: all
  become: yes
  roles:
    - common

- hosts: [leaders, databases]
  become: yes
  roles:
    - keepalived

- hosts: [stack-witness-1, databases]
  become: yes
  roles:
    - repmgr
    - postgres
