---
- hosts: all
  become: yes
  roles:
    - common
    - fancontrol

- hosts: leaders
  become: yes
  roles:
    - keepalived

- hosts: [stack-witness-1, databases]
  become: yes
  roles:
    - repmgr
    - postgres

- hosts: [leaders, workers]
  become: yes
  roles:
    - k3s
